### ISSUE TITLE
Meeting week 2

### ISSUE THREAD

**Issue by maryi** [maryi/CSCW-Project#12]
Hi team, @mpaskevi @eli4 @dustinfaulkner91 @kristalow 
We didn't agree on the time for our next meeting, but I think is important to have a meeting at the beginning of the week since we don't have to make any blog posts we can use the time for the project :) ...
**So, what about meeting Monday 4:30pm ??**
Please reply if you agree or not. Thanks!

**Comment by mpaskevi** [comment]
Monday 4:30pm works for me!

**Comment by eli4** [comment]
monday at 4:30 is fine with me

**Comment by kristalow** [comment]
4:30pm on monday works for me

**Comment by maryi** [comment]
Ok. then see you all at 4:30pm today.
May i remind you that this is a virtual meeting. We will meet in slack and then use @mpaskevi link/tool to connect.

**Comment by maryi** [comment]
We already met. so closing issue.
