### ISSUE TITLE
Project proposal

### ISSUE THREAD

**Issue by maryi** [maryi/CSCW-Project#13]
I'm still working on the Ethics (I'm in the 9th page out of 20) But I had some time to take a look at the proposal and made some comments.
I'll continue working on the Ethics and @mpaskevi will work on the proposal edition and general flow.
However, we still have some **empty** and **very incomplete sections** so we really need everyone's help.
Please @eli4 @dustinfaulkner91 @kristalow select two or three sections to help with and leave a message on this issue saying on what section you are going to work. Thanks a lot!

**Comment by eli4** [comment]
im doing some work on limitations,strategy and expected results

**Comment by maryi** [comment]
Project proposal was submitted, so closing this issue.
