### ISSUE TITLE
Week 2 - Create user requirements and define application descriptors

### ISSUE THREAD

**Issue by maryi** [maryi/CSCW-Project#14]
- [x] Create list of user requirements
- [x] Define application descriptors, based on MoCA and on our complementary research

**Comment by mpaskevi** [comment]
First draft: https://docs.google.com/spreadsheets/d/1TqLa4gHUFu1yPXL21nvnYt639jL6ufVpg50lL-hpFUo/edit#gid=792928667

**Comment by maryi** [comment]
Thanks @mpaskevi for your work :+1: .. i moved the link to the project report folder so we can all easily find it from there..
Just in  case you don't know.. you can clic on the "squares"  so you indicate that  you've finished that specific task.. Thank way we can keep track of progress

**Comment by eli4** [comment]
For the descriptors I would suggest adding a compatibility descriptor where the user can enter applications that go well with the one they are describing, for example GitHub and slack go well together. Also I'm not sure the creator descriptor is useful, i cant think of a reason we would want to list all the collaborative tools Microsoft has for example, I think people want collaborative tools that fit a specific purpose not ones that are from the same company. Lastly im not sure what is meant by authentication type.

**Comment by maryi** [comment]
:+1: I like @eli4 's idea.
Maybe we can just allow application name and link to get more information. Then, If any user is interested, they can just go into the link.
About authentication type.. I don't remember that either, sorry!. 
This confirms we need to define our vocabulary :)
