### ISSUE TITLE
Week 2 - Set up Website

### ISSUE THREAD

**Issue by maryi** [maryi/CSCW-Project#15]
- [x] Create a different folder for the project development 

Create the website for MatchMaker app using Github features. *ONLY visual interface*:
- [x] Create welcome page
- [x] Create page to search for an app -base development on mockups
- [x] Create page to register a new app in the database -base development on mockups

**Comment by maryi** [comment]
Hi, 
I'm leaving here some extra resource to help you with the website creation:
https://pages.github.com/
https://help.github.com/articles/creating-project-pages-manually/
https://help.github.com/articles/creating-pages-with-the-automatic-generator/

**Comment by maryi** [comment]
Hi @dustinfaulkner91,
We missed you at our meeting. How are you doing with the web development? do you need any help?
Please let us know.

**Comment by dustinfaulkner91** [comment]
Im doing OK.
Getting it figured out.

**Comment by dustinfaulkner91** [comment]
The websites are made, but they are going to need a little bit of work. I've been working on it the last 3 hours, but I need to keep reading on Git and HTML. I can't quite get the surveys to do what I want.

**Comment by maryi** [comment]
Hi @dustinfaulkner91 
I notice you reported your time in your personal log (.md).. I just wanted to let you know the Peggy ask us to move into a single spreadsheet to report our activities. This new file is in the same folder with the link. Please move and keep your activity report there.
Thanks!
