### ISSUE TITLE
Week 2 - Set up Database

### ISSUE THREAD

**Issue by maryi** [maryi/CSCW-Project#16]
- [x] In the project development folder create a folder for the database information
- [x] Set up the data base server
- [x] Add tables to the database based on the application descriptors.

**Comment by eli4** [comment]
currently waiting on uvic staff to respond with database information

**Comment by eli4** [comment]
I recieved an email back from uvic regarding using there database, It looks like if we use their database  we would have to connect from the Engineering LAN, meaning the website would be unable to communicate with the database outside the engineering and ecs buildings. Becuase of this I think it might be better if i just set up a virtual database using https://aws.amazon.com/free/ so we will be able to communicate to the database from anywhere. I'll probably begin setting up the amazon server today after I finish the mockups so if anyone disagrees with the decision try to post something here today.

**Comment by maryi** [comment]
:+1:  @eli4 
Agree with you, I don't like that restriction either...

**Comment by mpaskevi** [comment]
@eli4 Thanks for looking into this.  I agree with you both, we need a DB that is accessible for both building and deploying the app.

**Comment by eli4** [comment]
the database implementation is now done, hopefully during the rest of the week I will add all the apps we have currently listed to the database
