### ISSUE TITLE
Week 2 - Create list of base applications

### ISSUE THREAD

**Issue by maryi** [maryi/CSCW-Project#17]
- [x] Create a google spreadsheet and create a link to it on Github
- [x] Add in the first row the list of descriptors we will use for each application/tool.
- [x] Using the list of applications provided in #11, add each application to the spreadsheet and analyze its characteristics to define the descriptors. 

This list of base applications will be used on Week 3 to initially populate the database.

**Comment by kristalow** [comment]
list of base applications spreadsheet: https://docs.google.com/spreadsheets/d/1Trh6Pesxvv5aYfd_x7wXxGmR5k9Y5g7-wpFbezwqi8E/edit?usp=sharing

**Comment by kristalow** [comment]
compared my list of applications with the one's eli added to the spreadsheet and the descriptors we used are the same. i will add more applications to the list by wednesday.

**Comment by mpaskevi** [comment]
how is work going on this?  it does not appear that the list of apps is growing very quickly.

**Comment by kristalow** [comment]
it's good, i've been super busy with my other classes but i will definitely focus on adding some more to this list later today and during reading break.

**Comment by eli4** [comment]
we should probably update the list of base application to include the new descriptors of modality and others found here:https://docs.google.com/spreadsheets/d/1TqLa4gHUFu1yPXL21nvnYt639jL6ufVpg50lL-hpFUo/edit#gid=792928667

**Comment by kristalow** [comment]
thanks for the reminder @eli4 . i have updated the list of apps to include modality, learning curve, etc. and i removed authentication type.

i'm having some trouble classifying some apps for the 'content privacy' descriptor. (Private channels/ Open messages to registered users / Open messages to general public)
for example, some online whiteboards can only be seen by the select group of people who can edit it, so would i label it as Private Channel? or what if apps don't have chat/messaging features?

**Comment by mpaskevi** [comment]
Sorry for the delay @kristalow.  Some ideas 

Private channels - users can communicate to other group members privately or the group as a whole (Google Hangouts, Slack) 
Open messages to registered users in group - users can communicate to group as a whole only (Gliffy, GitHub) 
Open messages to general public - all communication visible to outside users (Twitter) 

Perhaps 'open messages' is not the best term to use here.  I might say 'open communication'?  That would cover collaboration beyond messaging and include contributions to a webpage, whiteboard, document, etc.  Does that help?

**Comment by kristalow** [comment]
@mpaskevi yes, thank you for the help. this will give me a good start on filling this section in for the app list.
