### ISSUE TITLE
Synchronous versus asynchronous 

### ISSUE THREAD

**Issue by mpaskevi** [maryi/CSCW-Project#18]
We had this discussion at our October 21 meeting.  Is the boundary between synchronous and asynchronous communication starting to blur?  Is GitHub a synchronous tool as Maryi argued, because we can read and respond in real time to each others contributions. What about Slack?  Lets keep this conversation going :)

**Comment by eli4** [comment]
perhaps instead of having users choose whether an app is synchronous or asynchronous it would be better to have a slider to indicate how strongly synchronous or asynchronous an app is

**Comment by kristalow** [comment]
i think that's a good idea @eli4 . some apps can have both synchronous and asynchronous communication, like slack for example. slack can be like instant messaging or it can also be like email since a person doesn't always respond to a message right away.

**Comment by maryi** [comment]
I like your idea @eli4, however I have a concern with that approach..what is going to be the scale to implement in the slider? and what it means each of the values on the scale? We have to define that so everyone using our app have the same idea when they choose that an app is "10" towards synchronous, for example..

**Comment by eli4** [comment]
a 1 could mean completely async, a 10 be completely sync, a 5 it supports both, 2-4 its more async then sync, and 6-9 its more sync than async. my question would be what apps would rate as a 1 (completely asynch) if we are using the definition discussed in our meeting on Wednesday, that a synchronous tool is one that produces some change instantly. with that definition is anything completely asynchronous?
