### ISSUE TITLE
mysql database server

### ISSUE THREAD

**Issue by eli4** [maryi/CSCW-Project#19]
could use some help finding a free mysql server.
@maryi @mpaskevi @kristalow  @dustinfaulkner91

**Comment by kristalow** [comment]
maybe try this one?
http://www.microsoft.com/web/platform/database/free-database.aspx

**Comment by eli4** [comment]
that would run a database off my computer but it wouldn't allow the application website to connect to it.what we need is a server that we can connect to over the internet.

**Comment by eli4** [comment]
https://aws.amazon.com/free/ i just found this one so unless anyone has other suggestions this is probably what ill end up using

**Comment by maryi** [comment]
i found this http://www.uvic.ca/systems/services/storagebackup/databaseadmin/index.php
I emailed them and I waiting for their answer... Maybe we can have the database on the Uvic servers.. we'll see :)

**Comment by maryi** [comment]
I also typed 'free mysql hosting' on google and i got a lot of websites that offer free hosting for MySQL databases...maybe take a look at that if there is something useful

**Comment by maryi** [comment]
Hi @eli4, 
The helpdesk people from Uvic replied and said they can host the database in their servers :)
We just need access and start creating the database.. I forwarded the email to your email address so you can continue with the conversations.
I sent the message to this address elif@uvic.ca.. let me know if you didn't get the message.
