### ISSUE TITLE
Meeting week 3

### ISSUE THREAD

**Issue by maryi** [maryi/CSCW-Project#20]
Hi everyone! @mpaskevi @eli4 @kristalow @dustinfaulkner91 
I think is good to have a meeting at the begining of the week to check how are we doing and make the plan for the week.
**Please make sure before the meeting you have updated your task issue with the progress you have made so we all can see what you've been working on and how can we all help.**

Do you have time to have the virtual meeting Monday at 4:30pm? just like last time

**Comment by eli4** [comment]
4:30 works fine for me

**Comment by kristalow** [comment]
monday at 4:30 works for me

**Comment by maryi** [comment]
Plan for the week:
Michael & Maryi: Work on descriptors and addressing Peggy's comments.
Krista: continue making the list of apps
Eli: DB implementation, update mockups
Dustin: continue with web development (?).  We don't have any news from him, waiting until wednessday meeting.
