### ISSUE TITLE
Week 3 - Work on descriptors and report

### ISSUE THREAD

**Issue by maryi** [maryi/CSCW-Project#22]
- [x] complete descriptors definiton
- [x] address Peggy's comments on the project report

**Comment by mpaskevi** [comment]
Ill be moving the report into markdown format here today.  

In the presentations yesterday there was reference to another interesting descriptor, the modal descriptor.  Modal describes the tool in terms of audio, video, document - however I think we could add more selections, thoughts?  Here is the reference: 

Nickerson, R. C. (1997). A taxonomy of collaborative applications. In Proceedings of the AIS 1997 Americas Conference on Information Systems (Vol. 52, pp. 560-562).

**Comment by kristalow** [comment]
has anyone made an issue for peggy's comments? i can make one if there hasn't been one made yet

**Comment by mpaskevi** [comment]
Please feel free @kristalow, thanks!  Make a checklist item for each issue we need to resolve.  I will only get to moving the proposal later this evening.
