### ISSUE TITLE
Peggy's Comments for Proposal

### ISSUE THREAD

**Issue by kristalow** [maryi/CSCW-Project#24]
Link to proposal pdf: https://slack-files.com/files-pri-safe/T0ACBS53K-F0D5FTWF3/matchmakerapp_proposal_feedback_from_peggy.pdf?c=1446150848-0216eb581ca8e3f2610551133660e59ab4d0cbfa

<b>Abstract:</b>
- [x] I think your abstract undersells what you may do -- but you can update this as you progress through your project. Also the way the abstract is written, there is a lack of a problem -- why do we need the framework at all?

<b>Introduction:</b>
- [x] Again start with the problem -- is it that choosing or comparing technologies to use in a particular context can be difficult? Or that there are competing frameworks/mechanisms to do that?
- [x] Perhaps put the challenge first, and then discuss the framework and that you will explore if it is viable for using it in the way you suggest.
- [x] Before you describe the MoCA framework, perhaps you need more general background?  A bit like the background in the Moca paper itself that discusses other frameworks that are around (and perhaps they missed some?).  And is there any other work that discusses how to select technologies to use in collaborative work -- I don't know of any offhand so perhaps not -- but check!   Or perhaps there are tools that one uses to select tools for other contexts (e.g., education).  This section doesn't have to be super long but it should show that you didn't just obsess on MoCA and forget to look at anything else.  Then you could have another section called the MoCA framework.

<b>Background:</b>

The MoCA Framework section:
- [x] Edit wording for Synchronicity 
- [x] Explain “predictability of time” in Synchronicty and “predictability of place” in Physical Distribution 
- [x] Say a bit more about the intent behind MoCA... and how it was applied in the MoCA paper.

Affordances of Collaborative Technologies section:
- [x] flow is lacking here in the reader... bring the reader with you as you switch topic...  how does this relate to the last section?  Are you still talking about MoCA or is this something else?   Or is this the background I asked for before? But as I read on here, I almost wonder if this should come in the background section I suggested as it somehow motivates why you look at MoCA? 
(if I understand the writing correctly) Do a "talk aloud" as you go through your paper and ask each other if the flow of content in terms of the story you are telling makes sense.
- [x] The writing needs improving a bit (in terms of flow between ideas)

<b>The Problem We Are Trying to Solve:</b>
- [x] I think I perhaps just wished to see this earlier
- [x] I think just order of writing can be improved as you work on next versions of your report
- [x] Recommender Systems reference - This seems important -- perhaps add more details?  Could you use this tool, I'm guessing not, but say why it is not adequate and why your work is needed in the context of this paper.

<b>Proposal/What Are We Going To Do?</b>
- [x] <i>Our application will also look to benefit from the knowledge on the people and will allow users to register information about applications</i> -  This sets off some alarm bells for me, will want to share this information, or take the time to share it...  I'm not saying they won't but check this assumption as early as you can (even through a mockup of some sort)

Figures of mockups:
- [x]  I wonder (and the reader would too) how you arrived at these designs?  Sort of a hunch you have or?
- [x] Make these bigger in your paper -- this is great progress that you are already working towards a solution. 
- [x] Of course these may change, for the purposes of the course, and if they do, you may want to keep these original designs in an appendix so that you show the process you followed.  

<b>Technical Specifications:</b>
- [x] Second paragraph of technical specifications - Put this in a separate section that discusses your team work -- it isn't related to the project per se -- in fact you could put it in an appendix.

<b>Strategy/Methods:</b>
- [x] <i>One of us will focus on implementing the website and another on implementing the database</i> - Which one of you?
- [x] You are mixing research methodology in with what your team will do -- for the next phase of the report -- separate this. 
- [x] For the milestones/roles -- this is a bit vague -- oh I see roles before --  you are making me work read this :)  Gather the project management/milestones/roles stuff in one place, and add much more details to your milestones.  Do this also for the interim report -- update it according to where you are there and show me what was completed so far by which member. 
- [ ] As I just mentioned your methodology should be in a separate section and it also needs to be clearer -- I suspect though by the interim report it will be ... add more details, commit to the design (and then change it as you need to) and justify your research design, why those methods and not others. Reference the literature we read on evaluation. 

<b>Limitations:</b>
- [ ] The biggest risk I see is that users may not want to accept or even ask for recommendations about which tools to use... can you test this out earlier somehow?   I tend to believe they will but I'm not 100% certain!

**Comment by kristalow** [comment]
I tried dividing them up into sections..but refer back to our proposal to get a better understanding of where she made the comments.

**Comment by maryi** [comment]
:+1: Thanks @kristalow !
team, remember to select the check box if you start working on any of these issues :)

**Comment by mpaskevi** [comment]
I like how you handled the sections @kristalow, I was wondering how to do this myself.  Perhaps we can have the PDF linked here as well so we can see specifically where Peggy made the comment in the document.

**Comment by kristalow** [comment]
thanks for the suggestion, i added the link to the proposal pdf at the top of the page.

**Comment by kristalow** [comment]
i've checked a few things off this list that i will be working on, so hopefully it hasn't been already completed. i'm going to add more details to the 'problem we're trying to solve' section, help out with the milestones, roles section.

**Comment by maryi** [comment]
comments were addressed on interim  report. Closing issue
