### ISSUE TITLE
Clarity on the naming of our application

### ISSUE THREAD

**Issue by mpaskevi** [maryi/CSCW-Project#27]
Throughout the report we have used different names for the application including: 

match maker application 
match maker app 
matchmaker app

Just to be consistent I think we should wed ourselves to one standard name.  I am proposing 'MatchMaker Application' as the standard. Please let me know if you have other ideas or want to go with something else.  

This should also be standardized in the mockups and the application itself.

**Comment by mpaskevi** [comment]
Since no one raised concern I have changed all references to the app to 'MatchMaker Application'

**Comment by dustinfaulkner91** [comment]
I would be interested in discussing a more... interesting name. I propose "Not P.O.F." Although, this is is probably not a pressing matter.
