### ISSUE TITLE
Remaining website work

### ISSUE THREAD

**Issue by eli4** [maryi/CSCW-Project#28]
all website materials can be found here: https://github.com/maryi/CSCW-Project/tree/master/Development/Web/turorial

- [x] First: @dustinfaulkner91  needs to edit the 3 HTML (mainly just registerIndex and searchIndex) to reflect the descriptor outline given by @maryi  here: https://docs.google.com/spreadsheets/d/1TqLa4gHUFu1yPXL21nvnYt639jL6ufVpg50lL-hpFUo/edit#gid=792928667

- [x] Second: I will then update the php files so the database uses the new descriptors for registering and searching.

Third: (this one can be done at any point) we need to decide how we want the search function to want IE how we are going to pick which results to recommend.

**Comment by kristalow** [comment]
here's an idea of what the website could look like with a header & stuff
![example](https://cloud.githubusercontent.com/assets/14945605/11082092/18f277c8-87d7-11e5-83a4-f331ef6b3570.png)

**Comment by mpaskevi** [comment]
That look great @kristalow!  What do you think @eli4 and @dustinfaulkner91, possible to style the site this way?

**Comment by eli4** [comment]
its 100% possible and I suspect it wouldnt take very much work to get it looking like this.

**Comment by mpaskevi** [comment]
Hi @dustinfaulkner91 @eli4 , I am seeing some differences between the app as it currently exists and our description in the project report document?  See https://github.com/maryi/CSCW-Project/blob/master/Project%20report/ReportDocument.md#11-explanation-of-user-requirements for the latest fields described for search and register an app.  

What are the chances we could bring the app in line with our report?  If its not possible before Friday we should have an explanation of why its not the same and our plan for deployment.

**Comment by mpaskevi** [comment]
@eli4 I am seeing that you have addressed this issue in the report just now.  So I am guessing it is not feasible for Friday?

**Comment by eli4** [comment]
there is a chance that ill have time to add this image to the html either tonight or tomorow afternoon. It depends on how fast I can finish some of my other school assignemnts. Otherwise maybe @dustinfaulkner91  could add it in when he is modifying the fields in the register and search page

**Comment by mpaskevi** [comment]
@eli4 @dustinfaulkner91 it would be great!  if it does get done please be sure to update the report as well.  we want to be sure our report matches our current prototype.

**Comment by dustinfaulkner91** [comment]
We're more focused on functionality at the moment. Making it pretty is easy enough after everything works properly. We may need to modify some descriptors for functionality's sake.

**Comment by mpaskevi** [comment]
Hi team, how is the application development going? I am hoping we can begin some user testing this week. Is there an estimate on when we might have the app in line with our latest document?

**Comment by eli4** [comment]
i was planning on implementing a possible search function today which is the only missing functional component. however the way the html was giving data was inconsistent with the list of base applications we have so i have to sort that out before doing the search function. hopefully i will still have time today to do both. after that all thats left is to make it look pretty and perhaps improve the search function if necessary

**Comment by eli4** [comment]
at the current rate of things it looks like in less than three hours, the website should have search functionality! from that point on there should only be minor modifcations needed, for example adding links on all the pages to the home page

**Comment by mpaskevi** [comment]
It looks like the app search page is out of sync with the current report document.  Is this the most up to date version of the app: http://turorial1-1120.appspot.com/search?  It is missing purpose which is supposed to a multi-select dropdown, likewise for domains of practice.  See: https://github.com/maryi/CSCW-Project/blob/master/Project%20report/ReportDocument.md#11-explanation-of-user-requirements

**Comment by eli4** [comment]
that is the current version of the app. Dustin is for the most part in charge of the html so i guess he is still working on that part. realisticly I would expect it to only be around an hour of work to add those features at most. If Dustin is busy and cant get around to adding those features I can try and do that as well i suppose but i might not be able to do it today.

**Comment by dustinfaulkner91** [comment]
I'm on it, I've been busy up until now.

**Comment by eli4** [comment]
alright dustin has now added the purpose field and i have implemented a search function, you can now test out the search function at: http://turorial1-1120.appspot.com/search. Hopefully now all major components of the website are done and we will just need to do a few minor tweaks.

**Comment by mpaskevi** [comment]
Nice progress guys! @eli4 I can not see your new search function, perhaps put it in another location as the /search page is currently for describing cscw work.  We could also change that page name to /describe  

I have found a few small things to change on the app.  Is there a way I can adjust the text?  Are the source files currently on GitHub?  

Thanks!

**Comment by maryi** [comment]
Same here.. I want to help with the development :)
@eli4 @dustinfaulkner91 Where can I find the source files?

**Comment by eli4** [comment]
all the files are under development/web/turorial

**Comment by eli4** [comment]
@mpaskevi  when you go to http://turorial1-1120.appspot.com/search and file out that survey and hit submit does it not return search results for you?

**Comment by maryi** [comment]
There is still this question when searching for an app: How many different areas of study is your team involved in?... This is communities of practice dimension, **which was replaced by Domains.**
I presumed this was taked from the mockups, remember that those are out of date.
Check the report to get more info.

**Comment by maryi** [comment]
Same thing when registering an app. The question :How many different areas of study can the application support is about the communities of practice, **which was also replaced by Domains**
Check the report.
