### ISSUE TITLE
Interim report sprint

### ISSUE THREAD

**Issue by mpaskevi** [maryi/CSCW-Project#29]
Hello all, 
As per our discussion online just now, we need everyone documenting their work on the MatchMaker Application project in the interim project report (https://github.com/maryi/CSCW-Project/blob/master/Project%20report/ReportDocument.md)  

@eli4 has agreed to contributing to the technical spec section, including details of the app development and linkages to DB. @dustinfaulkner91 we are hoping you could contribute here as well on the html development and enhancement.  Perhaps you guys could also look at the expected results and limitations section based on what you have experienced in development.  

I will be working on report on Wednesday morning and afternoon and will try to close off the remainder of Peggy's comments from the proposal - we have addressed nearly all of these but I want to review.  

@kristalow Agreed to review the final report before Friday and submit the document to Peggy.  If possible @eli4 @dustinfaulkner91 and I should have our contributions to the report done by Wednesday evening.  This will help @kristalow as she does her final review on Thursday and Friday. 
 
Remember that @maryi is not available this week.  

Lastly, in appendix 3 I have added dates to milestones not completed yet. Feel free to adjust if you believe these are not feasible.

**Comment by kristalow** [comment]
i decided to use latex to format our report..turns out it's not that hard to learn :) and i'm still trying to figure out how to upload a pdf (once the report is complete) to github.

**Comment by mpaskevi** [comment]
@kristalow I am signing off of the document at this point, I have completed my edits.  @eli4 @dustinfaulkner91 @maryi Please let Krista know when you have completed your edits, hopefully by end of day today, as she will do the final read through and submission on Friday.  Many thanks!

**Comment by kristalow** [comment]
i made a bunch of grammar & consistency changes (eg: app to application) to the report, but on the history it doesn't say that i made any of those changes even though the report has been updated with my changes.. i think i was editing the report at the same time as you @maryi so maybe the history was overwritten?

**Comment by maryi** [comment]
yes, I was making changes. Did you save yours??
If you did it shouldn't be a problem... I was working on a local copy, not on the web version

**Comment by kristalow** [comment]
the changes were saved but for some weird reason the history says i only made 1 commit, even though i did another commit before my most recent one.

**Comment by maryi** [comment]
jummm... no idea.. I hope it didn't deleted much from your edits..
Anyway.. I won't be modifiying anything else in the report (sorry if it was my fault :(   )..Now,  I'm completing the info in the APPENDIX 3

**Comment by kristalow** [comment]
don't worry it wasn't your fault @maryi, i was able to add in a few of the missing changes.


@maryi @mpaskevi @eli4 @dustinfaulkner91 are we finished editing the report? if so, i'm going to start formatting the report tonight.

**Comment by maryi** [comment]
Ok... I'm finish with my edits..
I'm pretty happy with the result.. Let's keep the awesome work team!!
I completed the info in the APPENDIX 3 and verified that we had a link from the report to it.
I won't be modifying anything else.. @kristalow I think now you are the only one working on the report.

**Comment by mpaskevi** [comment]
Just to confirm @kristalow, my edits are complete

**Comment by eli4** [comment]
my edits are complete as well

**Comment by maryi** [comment]
the interim report was submitted. Closing issue
