### ISSUE TITLE
Week 2 - Ethics application

### ISSUE THREAD

**Issue by maryi** [maryi/CSCW-Project#3]
- [x] Fill out Ethics application
- [x] Create APPENDIX 1: Email invitation to participants
- [x] Complete APPENDIX 2: Consent form
- [x] Create APPENDIX 3: Survey
- [x] Send complete Ethics application to Peggy for review
- [ ] Apply Peggy's suggested changes

**Comment by maryi** [comment]
I'm working on the project Ethics and I need to confirm some information with you..
The project name is: Match maker application, right?
And I need your Uvic emails please :)

**Comment by maryi** [comment]
@eli4 what is your last name?
@mpaskevi and @dustinfaulkner91 what is your uvic email account?

**Comment by mpaskevi** [comment]
I do not use uvic email.

**Comment by mpaskevi** [comment]
I might add 'software affordances' to the keywords

**Comment by maryi** [comment]
@mpaskevi i'll add the keyword. 
Also, the ethics application requires an uvic account. it says that I can provide a different email as the preffered address, BUT the uvic email must be in the application.

**Comment by mpaskevi** [comment]
mpaskevi@uvic.ca

**Comment by maryi** [comment]
Thanks! @mpaskevi .. I think this is just to confirm the affiliation with Uvic

**Comment by eli4** [comment]
my last name is ferguson and my uvic emial is elif@uvic.ca

**Comment by kristalow** [comment]
my email is kmlow@uvic.ca

**Comment by maryi** [comment]
Thanks!
i'm still missing @dustinfaulkner91 uvic's email

**Comment by maryi** [comment]
I'm choosing the method of survey in our methodology.. If you don't agree with that, please let me know

**Comment by maryi** [comment]
I just finished the Ethics application with all the attachments: Participant consent form, invitation email and survey.
