### ISSUE TITLE
Uploading pdf to Github

### ISSUE THREAD

**Issue by kristalow** [maryi/CSCW-Project#30]
I'm having some trouble learning how to upload a pdf to github (this is necessary to submit our interim report). i set up git on terminal/command prompt and cloned the repo to my laptop but i'm not sure how to add files to the repo from terminal. if anyone knows how to upload files, please let me know! i don't want to try and figure this out on the day our report is due.

**Comment by eli4** [comment]
to upload the pdf I would do the following
1. open git shell
2. clone the repo
3. add the pdf to the place on the local (cloned repo) that you want it to be on github
4.git add <name of pdf>
5. git commit -m <"any comment you want to add with your pdf commit">
6.git push

**Comment by kristalow** [comment]
thanks for the help @eli4 !! :) i was able to upload a test pdf to github using the steps

**Comment by mpaskevi** [comment]
@kristalow please close this issue if resolved.
