### ISSUE TITLE
Meeting with Peggy week nov 16

### ISSUE THREAD

**Issue by maryi** [maryi/CSCW-Project#31]
@mpaskevi  posted:
peggy is requesting team meetings next week.  I can come in virtually on Monday or Tuesday at 4pm?  Does that work for anyone else?

**Comment by eli4** [comment]
those times work for me

**Comment by maryi** [comment]
@kristalow said: im able to meet on monday at 4, but tuesday doesn't work for me
as for me... I can do Monday

**Comment by maryi** [comment]
I sent a request to Peggy for meeting on Monday 4pm.. still waiting her confirmation :)

**Comment by maryi** [comment]
Peggy confirmed the time :)
Monday 16th at 4pm

**Comment by mpaskevi** [comment]
Great, I will have to come in via skype or google hangouts.  Would someone be willing to bring their laptop or tablet to be my personal portal to the meeting?

**Comment by kristalow** [comment]
@mpaskevi i will have my laptop with me on monday and i can use either Skype or google hangouts, whatever is easiest.

**Comment by mpaskevi** [comment]
@kristalow Thank you, I will come in via our weekly meeting hangout room.  

https://hangouts.google.com/call/ej5z6rzjzoyge2ihmvb7liqxoaa

**Comment by maryi** [comment]
Peggy's office is in ECS 562

**Comment by mpaskevi** [comment]
@kristalow I am in the hangout
