### ISSUE TITLE
uploading interim report

### ISSUE THREAD

**Issue by kristalow** [maryi/CSCW-Project#32]
i'm having some trouble uploading the file to github again. i think it's because my local repo isn't updated with the most recent changes.. i tried googling it, but i still can't get it to work. anyone have any ideas?
i will still try to figure out how to upload it, but if i still can't get it to work, can somebody else upload the report? thanks!

[InterimReport.pdf](https://github.com/maryi/CSCW-Project/files/33392/InterimReport.pdf)

it was my first time using latex so the formatting may not be perfect.. but i tried
if anyone knows latex and can fix up some of the formatting, here's the link: https://www.sharelatex.com/project/5641413aafa51cf857bc36be
(the appendices were made in word and then added to the pdf so they're not included in the link above)

**Comment by eli4** [comment]
if you into the main project directory and do a git pull it should update your repo and then after that you can push the changes

**Comment by kristalow** [comment]
@eli4 i tried doing a git pull and push and it still doesn't seem to work, but thanks for the help
@maryi i know that you have more experience using github, so do you think you would be able to upload the report? i still can't figure out how to update my local repo & uploading the file.

**Comment by maryi** [comment]
Hi @kristalow ..
send me the files you're trying to upload to my gmail... I can upload the files :)
PD: My email is in our slack channel

**Comment by maryi** [comment]
Hey team..
I just uploaded the pdf version of the report. I also created in the main page a link to it, so Peggy can easily find it :)
