### ISSUE TITLE
Peggy's comments from meeting Nov 16

### ISSUE THREAD

**Issue by maryi** [maryi/CSCW-Project#33]
- [x] Make more clear why we changed the MoCA 
- [x] Intro still lacks statement of issue at hand, it comes later in the report but needs to come out in the intro and abstract. 
- [x] Crisp explanation of our proposal in the introduction
- [x] Furthermore, description of what are we doing above and beyond what MoCA already does should be in intro and abstract.  What are we adding?  Using as a basis for recommender app
- [x] Some issues with english grammar in report, was hoping these would be fixed in paper review.  Reiterate over the language of the report. Check for English language issues.
- [x] Describe cases of CSCW as previously described using MoCA, perhaps drawn from Lee and Paine paper.  
- [x] Get to user testing phase!  Run it by folks asap.  4-6 users providing feedback appropriate as per Peggy. 
- [x] Update Ethics: amend the recruitment of participants.
- [x] Add methodology section, fully describe our process so far (drawing from issue discussions in GitHub) then user testing phase 
- [x] State how "her"(from research papers) MoCA review does NOT give recommendations on tools for collaborative work.
- [x] Descriptors for collaborative work and tool features made into their own (new) section.
- [ ] Make tech. specs. its own section
- [x] Roles and contrubutions should be in Appendix 3
- [ ] update limitations section.
- [x] State the benefits of articulation, not just application-finding.

- [ ] For the LateX doc: Make the figures bigger

- [ ] Each person needs to write a summary of their contributions, should be in an appendix

**Comment by dustinfaulkner91** [comment]
updated the list to reflect the notes I took

**Comment by maryi** [comment]
@dustinfaulkner91 I think with your addition in the list deleted some of the stuff i had before. Just to be careful next time

**Comment by eli4** [comment]
im currently working on updating the tech specs to reflect the state of the website

**Comment by kristalow** [comment]
When we finish the report, I can format it in latex again but somebody will have to upload it on github since i was having a lot of trouble with it last time.

**Comment by mpaskevi** [comment]
Could everyone be more specific about where they will be contributing to the report?  Just post a comment here letting us know what section you will be working on.  

I am working on tackling the first few issues from Peggy: 

-Make more clear why we changed the MoCA
-Intro still lacks statement of issue at hand, it comes later in the report but needs to come out in the intro and abstract.
-Crisp explanation of our proposal in the introduction
-Furthermore, description of what are we doing above and beyond what MoCA already does should be in intro and abstract. What are we adding? Using as a basis for recommender app

I hope to complete these today.  Tomorrow I can review the survey feedback and start writing that section of the report.  

I will also be watching and correcting grammar and language issues as Peggy identified.

**Comment by eli4** [comment]
Im going to work on updating the technical specifications, expected results, and limitations sections

**Comment by kristalow** [comment]
i worked on describing cases of CSCW using MoCA from the Lee and Paine paper, i will be adding some notes about the survey based on feedback i got from friends, help out with editing, and format the paper

**Comment by mpaskevi** [comment]
can whoever wrote this please clarify what this means:  

State how "her"(from research papers) MoCA review does NOT give recommendations on tools for collaborative work.

**Comment by mpaskevi** [comment]
@maryi please let me know when you are finished with the methodology section as I would like to review and edit.

**Comment by mpaskevi** [comment]
Question, in a few spots someone is using the a "-" around a word.  for example see "-descriptors-" in methodology section. I dont understand this notation, is it needed for latex or Github perhaps?  I would suggest perhaps quotes (") rather than dashes (-)

**Comment by eli4** [comment]
regarding State how "her"(from research papers) MoCA review does NOT give recommendations on tools for collaborative work.

Im not the one who wrote that but I think it means explain how the original moca paper does not use the moca framework for recommending collaborative tools.

**Comment by maryi** [comment]
Hi,
I did 
*  Roles and contrubutions should be in Appendix 3
and now I'm finishing with:
* Descriptors for collaborative work and tool features made into their own (new) section.
* Add methodology section, fully describe our process so far (drawing from issue discussions in GitHub) then user testing phase
 
I plan to finish these sections today :)

**Comment by maryi** [comment]
Descriptors for collaborative work and tool features made into their own (new) section is DONE

Please give it a read :)

**Comment by maryi** [comment]
I just finished the methodology section :)

**Comment by eli4** [comment]
looks good ill work on editing the methodology section as well as the descriptors for collaborative work and tool features, today and tomorrow.

**Comment by eli4** [comment]
I edited the methodology section but there are 2 things im unsure of. First in this section we refer to ourselves as researchers which is probably fine but we done refer to ourselves as researchers anywhere else in the paper so im not sure. The other is a sentence I bolded in the second paragraph where im just not sure what the sentence is suppose to mean.

**Comment by mpaskevi** [comment]
@eli4 I am reading the report now, I do not see a problem with the use of 'the researchers' in this section.  At this point we collectively were making many decisions so this seems appropriate.  

Good catch on "The criteria followed to modify the list of descriptors was based on the information usefulness a descriptor could provide for the recommendation system. " It is a little unclear, I will try to tighten it up this morning.  I think what is being said is that as we were modifying the descriptors for tools, we were keeping in mind how they would map to the description of CSCW and become useful for the recommendation algorithm.  Nice catch!

**Comment by maryi** [comment]
Thanks @eli4 !... Methodology section looks better!
About the sentence, I think @mpaskevi has the idea. I was trying to say that everytime we considered to modify the descriptors, we evaluated how useful the information on the particular descriptor was for the system.

**Comment by mpaskevi** [comment]
I am wondering about the section which follows methodology, Strategy and Methods.  I believe it was written quite a while ago. It also shows old screenshots of the app. Perhaps we could have both the old and new screenshots, showing the development of the app from conception to production.  I think the text here could also be updated and flow better from the methodology section.  Any volunteers?

**Comment by maryi** [comment]
@mpaskevi you're right, that section needs to be updated to flow better with the other sections. 
The figures in the section are not screenshots, those are the mockups and I think it is ok to show them there... However, we should have screenshoots of the final product somewhere later in the report.. I'm not sure where, maybe in expected results?
I can work on that section on the afternoon is that's fine.

**Comment by mpaskevi** [comment]
I have added the remaining issues to https://github.com/maryi/CSCW-Project/issues/40
