### ISSUE TITLE
Meeting November 23 @ 4:30pm? 

### ISSUE THREAD

**Issue by mpaskevi** [maryi/CSCW-Project#38]
Hi group, are we meeting today via hangouts @ 4:30pm?  I have been away at a conference so love to catch up and see where we are at.  

Please let me know

**Comment by kristalow** [comment]
i will be out all afternoon so i won't be able to go online for the meeting, if there is one happening today.

**Comment by eli4** [comment]
im available for a meeting

**Comment by maryi** [comment]
I can be in the meeting too.

**Comment by mpaskevi** [comment]
Here is the link to the meeting, see you at 430 - https://hangouts.google.com/call/ej5z6rzjzoyge2ihmvb7liqxoaa
