### ISSUE TITLE
the 9th dimension is "Purpose"?

### ISSUE THREAD

**Issue by maryi** [maryi/CSCW-Project#7]
Again, working on the app design...
And I just feel something is missing in the framework. If I look for apps using this framework I would get in the same search Skype and Trello.. and they shouldn't because although both are for collaborative work, the first on is for communication while the later is for planning...
What do you guys think?

**Comment by mpaskevi** [comment]
Perhaps purpose can be described according to Bower's typology? I think there is actually room for us to expand upon this typology (http://www.downes.ca/files/images/Web_2.0_Technologies.PNG)  

I have popped the topology in text form in this google doc, perhaps we can work to expand and use this field to connect with purpose as a further dimension.

https://docs.google.com/spreadsheets/d/1TqLa4gHUFu1yPXL21nvnYt639jL6ufVpg50lL-hpFUo/edit?usp=sharing

**Comment by maryi** [comment]
@mpaskevi i like this idea. 
However, looking at the Bower's typology, how would you classify Github? i think this tool cannot be placed in just one classification.. but then, it could be multiple 'types' at the same time? A synchronous collaboration tool, Website creation tool and a social networking system??
What do you think?

**Comment by mpaskevi** [comment]
@maryi Agreed there will be some overlap in the categories, I believe we can use multiple to describe an application.  We will also have at least the seven other dimensions to describe the application which will hopefully help the matching process to the CSCW.

**Comment by maryi** [comment]
We approved purpose as an extra descriptor for collaborative work. More details about the rationale can be found on the interim report.
