### ISSUE TITLE
App - function registering an application

### ISSUE THREAD

**Issue by maryi** [maryi/CSCW-Project#9]
**Planned Permanence dimension**

I think we shouldn't have this dimension in the specific case when the user is registering a new app into the system .... We can decide about this based on different information.
 
For instance:
We can ask the user if the the app is web based, if it is free, if it requires to download an installer, if you need to register in order to use it.. and then on the back of our system we can create a hierarchy. Say:
 
For Planned permanence LOW to HIGH
Web based - free
Web based - free - with registration
Desktop app - free
Desktop app - free - with registration
Web based - payed - with registration
Desktop app - payed - with registration
 
What do you think?

**Comment by mpaskevi** [comment]
I am thinking make this selection non-exclusive.  Perhaps for low planned permanence apps which are free and easily accessible are ordered first.  

We should get some mock ups of the app display page wireframed so we can start imaging what that page looks like after users enter their MoCA description.
